import { supabase } from '@/integrations/supabase/client';
import { normalizeAnswer } from './normalize';
import type { Tables } from '@/integrations/supabase/types';

export type DbPrompt = Tables<'prompts'>;
export type DbAnswer = Tables<'answers'>;
export type DbWord = Tables<'words'>;
export type DbImportSource = Tables<'import_sources'>;

export function getSessionId(): string {
  let sid = localStorage.getItem('jinx_session_id');
  if (!sid) {
    sid = 'sess_' + Math.random().toString(36).slice(2);
    localStorage.setItem('jinx_session_id', sid);
  }
  return sid;
}

// --- Prompts ---
export async function getActivePrompts(): Promise<DbPrompt[]> {
  const { data, error } = await supabase
    .from('prompts')
    .select('*')
    .eq('active', true)
    .order('created_at');
  if (error) throw error;
  return data ?? [];
}

// Ensure daily prompts exist — calls edge function if none found
export async function ensureDailyPrompts(): Promise<DbPrompt[]> {
  let prompts = await getActivePrompts();
  if (prompts.length >= 3) return prompts;

  // Call edge function to generate prompts
  try {
    const { data, error } = await supabase.functions.invoke('generate-daily-prompts');
    if (!error) {
      // Re-fetch after generation
      prompts = await getActivePrompts();
    }
  } catch {
    // Silently fail — prompts may be generated by cron
  }
  return prompts;
}

export async function getArchivePrompts(): Promise<DbPrompt[]> {
  const { data, error } = await supabase
    .from('prompts')
    .select('*')
    .eq('mode', 'archive')
    .order('date', { ascending: false })
    .order('created_at');
  if (error) throw error;
  return data ?? [];
}

export async function getPromptById(id: string): Promise<DbPrompt | null> {
  const { data, error } = await supabase
    .from('prompts')
    .select('*')
    .eq('id', id)
    .maybeSingle();
  if (error) throw error;
  return data;
}

// --- Answers ---
export async function hasSubmitted(promptId: string): Promise<boolean> {
  const sid = getSessionId();
  const { count, error } = await supabase
    .from('answers')
    .select('*', { count: 'exact', head: true })
    .eq('prompt_id', promptId)
    .eq('session_id', sid);
  if (error) throw error;
  return (count ?? 0) > 0;
}

export async function getUserAnswer(promptId: string): Promise<DbAnswer | null> {
  const sid = getSessionId();
  const { data, error } = await supabase
    .from('answers')
    .select('*')
    .eq('prompt_id', promptId)
    .eq('session_id', sid)
    .maybeSingle();
  if (error) throw error;
  return data;
}

export async function submitAnswer(promptId: string, rawAnswer: string): Promise<DbAnswer> {
  const sid = getSessionId();
  const { data, error } = await supabase
    .from('answers')
    .insert({
      prompt_id: promptId,
      session_id: sid,
      raw_answer: rawAnswer,
      normalized_answer: normalizeAnswer(rawAnswer),
    })
    .select()
    .single();
  if (error) throw error;
  return data;
}

export interface AnswerStat {
  normalized_answer: string;
  count: number;
  percentage: number;
  rank: number;
}

export async function getStats(promptId: string): Promise<AnswerStat[]> {
  const { data, error } = await supabase
    .from('answers')
    .select('normalized_answer')
    .eq('prompt_id', promptId);
  if (error) throw error;

  const counts: Record<string, number> = {};
  for (const row of data ?? []) {
    counts[row.normalized_answer] = (counts[row.normalized_answer] || 0) + 1;
  }

  const total = Object.values(counts).reduce((s, c) => s + c, 0);
  return Object.entries(counts)
    .sort((a, b) => b[1] - a[1])
    .map(([word, count], i) => ({
      normalized_answer: word,
      count,
      percentage: total > 0 ? Math.round((count / total) * 100) : 0,
      rank: i + 1,
    }));
}

export async function getTotalSubmissions(promptId: string): Promise<number> {
  const { count, error } = await supabase
    .from('answers')
    .select('*', { count: 'exact', head: true })
    .eq('prompt_id', promptId);
  if (error) throw error;
  return count ?? 0;
}

// --- Words ---
export async function getWords(): Promise<DbWord[]> {
  const { data, error } = await supabase
    .from('words')
    .select('*')
    .order('word');
  if (error) throw error;
  return data ?? [];
}

export async function updateWord(id: string, updates: Partial<DbWord>): Promise<DbWord | null> {
  const { data, error } = await supabase
    .from('words')
    .update(updates)
    .eq('id', id)
    .select()
    .single();
  if (error) throw error;
  return data;
}

export async function importWordsFromCSV(csvText: string, sourceName: string): Promise<number> {
  const lines = csvText.trim().split('\n');
  if (lines.length < 2) return 0;

  const headers = lines[0].split(',').map(h => h.trim().toLowerCase());
  const wordIdx = headers.indexOf('word');
  const catIdx = headers.indexOf('category');
  const statusIdx = headers.indexOf('status');
  const sourceIdx = headers.indexOf('source_sheet');

  if (wordIdx < 0) return 0;

  // Get existing words to deduplicate
  const existing = await getWords();
  const existingSet = new Set(existing.map(w => w.word.toLowerCase()));

  const newWords: { word: string; category: string; source: string; status: string; jinx_score: number }[] = [];

  for (let i = 1; i < lines.length; i++) {
    const cols = lines[i].split(',').map(c => c.trim());
    const word = cols[wordIdx];
    if (!word || existingSet.has(word.toLowerCase())) continue;

    newWords.push({
      word: word.toLowerCase(),
      category: catIdx >= 0 ? cols[catIdx] : 'Uncategorized',
      source: sourceIdx >= 0 ? cols[sourceIdx] : sourceName,
      status: statusIdx >= 0 ? cols[statusIdx] : 'unreviewed',
      jinx_score: Math.floor(Math.random() * 40) + 50,
    });
    existingSet.add(word.toLowerCase());
  }

  if (newWords.length === 0) return 0;

  // Batch insert in chunks of 100
  for (let i = 0; i < newWords.length; i += 100) {
    const chunk = newWords.slice(i, i + 100);
    const { error } = await supabase.from('words').insert(chunk);
    if (error) throw error;
  }

  // Record import source
  await supabase.from('import_sources').insert({
    name: sourceName,
    rows_imported: newWords.length,
  });

  return newWords.length;
}

export async function bulkUpdateStatus(fromStatus: string, toStatus: string): Promise<void> {
  const { error } = await supabase
    .from('words')
    .update({ status: toStatus })
    .eq('status', fromStatus);
  if (error) throw error;
}

export async function getImportSources(): Promise<DbImportSource[]> {
  const { data, error } = await supabase
    .from('import_sources')
    .select('*')
    .order('created_at', { ascending: false });
  if (error) throw error;
  return data ?? [];
}

// --- Admin: Answer Cleaning ---
export async function mergeAnswers(promptId: string, sourceNormalized: string, targetNormalized: string): Promise<number> {
  // Count affected rows first
  const { count } = await supabase
    .from('answers')
    .select('*', { count: 'exact', head: true })
    .eq('prompt_id', promptId)
    .eq('normalized_answer', sourceNormalized);

  // Update all source answers to target
  const { error } = await supabase
    .from('answers')
    .update({ normalized_answer: targetNormalized.toLowerCase().trim() })
    .eq('prompt_id', promptId)
    .eq('normalized_answer', sourceNormalized);
  if (error) throw error;

  return count ?? 0;
}

export async function deleteAnswersByNormalized(promptId: string, normalizedAnswer: string): Promise<number> {
  const { count } = await supabase
    .from('answers')
    .select('*', { count: 'exact', head: true })
    .eq('prompt_id', promptId)
    .eq('normalized_answer', normalizedAnswer);

  const { error } = await supabase
    .from('answers')
    .delete()
    .eq('prompt_id', promptId)
    .eq('normalized_answer', normalizedAnswer);
  if (error) throw error;

  return count ?? 0;
}

// --- JINX Score (client-side for MVP) ---
export function getJinxScoreBreakdown(word: DbWord) {
  const s = word.jinx_score;
  const metrics = [
    { name: 'Linkability', weight: 0.25, score: Math.min(100, Math.max(0, s + ((hashCode(word.word + 'link') % 15) - 5))) },
    { name: 'Recognition', weight: 0.20, score: Math.min(100, Math.max(0, s + (hashCode(word.word + 'recog') % 10))) },
    { name: 'Cluster Health', weight: 0.15, score: Math.min(100, Math.max(0, s + ((hashCode(word.word + 'cluster') % 20) - 10))) },
    { name: 'Replay Value', weight: 0.15, score: Math.min(100, Math.max(0, s + ((hashCode(word.word + 'replay') % 10) - 5))) },
    { name: 'Uniqueness', weight: 0.10, score: Math.min(100, Math.max(0, s + ((hashCode(word.word + 'unique') % 15) - 5))) },
    { name: 'Overuse Risk', weight: 0.10, score: Math.min(100, Math.max(0, 100 - s + (hashCode(word.word + 'overuse') % 20))) },
    { name: 'Dead Prompt Risk', weight: 0.05, score: Math.min(100, Math.max(0, 100 - s + (hashCode(word.word + 'dead') % 15))) },
  ];
  return metrics.map(m => ({ ...m, weighted: Math.round(m.weight * m.score) }));
}

function hashCode(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) - hash) + str.charCodeAt(i);
    hash |= 0;
  }
  return Math.abs(hash);
}
